<a href="https://colab.research.google.com/github/NgocCanh2002/Colab-cua-Ngoc-Canh/blob/main/11_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0], [1,0], [0,1], [1,1]]
y = [0,1,1,1]
model = Perceptron()
model.fit(x,y)
print(' Do chinh xac', model.score(x,y))
x_test = [[1.5,2],[0.5,-0.5],[0.6,-0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

 Do chinh xac 1.0
[1 0 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0], [1,0], [0,1], [1,1]]
y = [1,1,0,0]
model = Perceptron()
model.fit(x,y)
print(' Do chinh xac', model.score(x,y))
x_test = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y_test = model.predict(x_test)
print(y_test)

 Do chinh xac 1.0
[1 0 1 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/data_crab.csv'
dataframe=pd.read_csv(url)


In [ ]:
import pandas as pd
url = '/content/crabs.csv'
data = pd.read_csv(url)
data

speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
#train_step_list: chia dữ liệu
from sklearn.model_selection import train_test_split 
import pandas as pd
url = '/content/crabs.csv'
data = pd.read_csv(url)
x= data.drop(['speies','sex'],axis = True)
y= data['sex']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
x

index  fontallip  rearwidth  length  width  depth
0        1        8.1        6.7    16.1   19.0    7.0
1        2        8.8        7.7    18.1   20.8    7.4
2        3        9.2        7.8    19.0   22.4    7.7
3        4        9.6        7.9    20.1   23.1    8.2
4        5        9.8        8.0    20.3   23.0    8.2
..     ...        ...        ...     ...    ...    ...
195     46       21.4       18.0    41.2   46.2   18.7
196     47       21.7       17.1    41.7   47.2   19.6
197     48       21.9       17.2    42.6   47.4   19.5
198     49       22.5       17.2    43.0   48.7   19.8
199     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 6 columns]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

crab = 'crabs.csv'
crab_data = pd.read_csv(crab)
data = (crab_data.drop('speies',axis = 1)).drop('index',axis = 1)
data.replace(to_replace ='M',value = 1)
data.replace(to_replace ='F',value = 0)

x_train = [data['fontallip'], data['rearwidth'], data['length'], data['width'], data['depth']]
y_train = data['sex']
x = np.reshape(x_train,(200,5))
y = np.reshape(y_train,(200))

model = Perceptron()
model.fit(x,y)
print('Độ chính xác',model.score(x,y))
x_test = [[15, 9, 10 ,10 , 8]]
y_test = model.predict(x_test)
print('sex: ',y_test)

Độ chính xác 0.5
sex:  ['M']


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "crabs.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)

print("Độ chính xác: ", model.score(x_train,y_train))
x_input = [[12.6,10,27.7,31.7,11.4], [13.3,11.1,27.8,32.3,11.3]]
y_pred = model.predict(x_input)
print(y_pred)

Độ chính xác:  0.8642857142857143
[1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "crabs.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[8.1,6.7,16.1,19,7], [9,8.5,19.3,22.7,7.7]]
y_pred = model.predict(x_input)

print(y_pred)

Độ chính xác:  0.9357142857142857
[0 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "/content/iris.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[8.1,6.7,16.1,19,7], [9,8.5,19.3,22.7,7.7]]
y_pred = model.predict(x_input)

print(y_pred)

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác: ', model.score(x_train,y_train))
x_input = [[4.7,3.2,1.3,0.2],[5,3.6,1.4,0.2],[4.4,2.9,1.4,0.2]]
y_pred = model.predict(x_input)
print(y_pred)

Độ chính xác:  1.0
[1 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác: ', model.score(x_train,y_train))
x_input = [[5,3,1.6,0.2],[5,3.4,1.6,0.4],[7,3.2,4.7,1.4]]
y_pred = model.predict(x_input)
print(y_pred)


Độ chính xác:  1.0
[1 1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
